<?php

	// Connect to database.
	$db = mysqli_connect("localhost", "meteor", "xpF7mBWqMtvJUpt9", "meteor");

?>
<table border="1">
<?

/*******************************************************************************************
+==========================================================================================+
|-------------------- How to use procedure getReservedCoursesIds --------------------------|
+==========================================================================================+
********************************************************************************************/

	$reserved = array();

	// Use the procedure.
	$res = mysqli_query($db, "CALL getReservedCoursesIds(62)");

	// Fetch results.
	while($r=mysqli_fetch_assoc($res)) {
		if ($r["conflicting"]) {
			// If conflicting, then
			$reserved[strval($r["course_id"])] = -1;
		} else {
			$reserved[strval($r["course_id"])] = 1;
		}
	}

	// Burn all results generated by CALL [procedure].
	// They appear to ALWAYS generate more than one result
	//	which causes errors with subsequent MySQL calls when not burnt....
	while (mysqli_more_results($db) && mysqli_next_result($db));


/*******************************************************************************************
+==========================================================================================+
|-------------------- Core code ends here -------------------------------------------------|
+==========================================================================================+
********************************************************************************************/

	$res = mysqli_query($db, "SELECT * FROM courses");
	while($r=mysqli_fetch_assoc($res)) {
		echo "<tr";
		if (isset($reserved[$r["id"]])) {
			if ($reserved[$r["id"]] == -1) {
				echo " style=\"background-color:#FF0000\"";
			} else if ($reserved[$r["id"]] == 1) {
				echo " style=\"background-color:#00FF00\"";
			}
		}
		echo ">";
		foreach($r as $i=>$v) {
			echo "<td>".$v."</td>";
		}
		echo "</tr>";
	}
?>
</table>
<?

/*
	if (isset($_COOKIE['name'])) {
		$res = mysqli_query($db, 
						"SELECT courses.id,
								courses.name,
								courses.description,
								DATE_FORMAT(`start`, '%b %d %Y') AS `start`,
								DATE_FORMAT(courses.end, '%b %d %Y') AS end,
								courses.cost,
								courses.venue,
								courses.available,
								courses.reserved,
								courses.paid,
								DATE_FORMAT(reserved.date, '%b %d %Y %h:%i %p') AS date
						 FROM sessions
						 JOIN reserved
						 ON sessions.user_id = reserved.user_id
						 JOIN courses
						 ON reserved.course_id = courses.id
						 WHERE sessions.token = '".$_COOKIE['name']."'
						 AND `start` >= CURDATE()
						 ORDER BY date DESC;");
		$data['success'] = 1;						  
		while ($rec = mysqli_fetch_assoc($res)) {
			array_push($data['courses'], $rec);
		}
	}
	else {
		$data['success'] = 0;
	}
	echo json_encode($data);
*/

?>
